services:
  - type: web
    name: eduvault
    env: python
    plan: free
    pythonVersion: 3.12.13
    repo: https://github.com/azhaganece/eduvalut2.git
    branch: main
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python app.py
